### ISSUE TITLE
CLIP为啥还有个解码器

### ISSUE THREAD

**Issue by TinyQi** [ZHEQIUSHUI/CLIP-ONNX-AX650-CPP#1]
感谢楼主的代码贡献，阅读了您的代码后，我发现您代码中有decode相关的内容，我看CLIP的论文是只有图像编码器和文本编码器的，在您的代码中为啥会多出一个解码器呢？
这个解码器是否就是最后图像特征和文本特征点积操作呀？

另外，不情之请，怪不好意思的，楼主可以提供一下你demo里使用到的相关模型吗？百度云之类的都行，拜托楼主了。

**Comment by ZHEQIUSHUI** [comment]
https://github.com/ZHEQIUSHUI/CLIP-ONNX-AX650-CPP/releases
模型都在这，解码器算是我的命名错误。。。现在分成了 图像编码器和文本编码器和一个特征matmul的onnx

**Comment by TinyQi** [comment]
楼主好，我尝试了您最新的代码和配套的模型，目前结果是准确的，谢谢楼主！！

**Comment by TinyQi** [comment]
![image](https://github.com/ZHEQIUSHUI/CLIP-ONNX-AX650-CPP/assets/28993936/cb4918b7-bdfa-4ee5-ae04-e4f759aea20f)

**Comment by TinyQi** [comment]
楼主，我有点好奇您这边是怎么导出onnx模型的，对于onnx部署，我是个新手，我想观摩一下您的模型导出代码，学习学习，不知道可以不？

**Comment by ZHEQIUSHUI** [comment]
我整理一下，明天更新在readme

**Comment by ZHEQIUSHUI** [comment]
已更

**Comment by TinyQi** [comment]
谢谢楼主啦，大大滴好人
