### ISSUE TITLE
打开CUDA支持，但是并未能调起GPU

### ISSUE THREAD

**Issue by TinyQi** [ZHEQIUSHUI/CLIP-ONNX-AX650-CPP#2]
楼主你好，我已经完成的CPU上的推理测试，但是当我想转到GPU上运行程序时，发现并未生效。
我的操作就是打开你代码中的注释，在OnnxWarpper.hpp文件中：
OrtSessionOptionsAppendExecutionProvider_CUDA

![image](https://github.com/ZHEQIUSHUI/CLIP-ONNX-AX650-CPP/assets/28993936/1cd3ccd0-5554-44b3-96a3-7947ba3bc935)

请问除了打开这个注释以外，还需要其他的配置吗?我机器上的CUDA是10.1版本的，然后驱动418.87。

**Comment by ZHEQIUSHUI** [comment]
你的是gpu版本的onnxruntime么
我这边也没用过gpu

**Comment by TinyQi** [comment]
楼主晚上好，我最后确实是调起来了。只要驱动版本和cuda版本都对的情况下，是能调起来的。

**Comment by TinyQi** [comment]
但是我现在有个问题，就是我们公司的老环境驱动不可能更新，所以我必须要将onnx的模型降版本，我现在正在操作呢
